name: Build & test

on: push

jobs:   
  build-test: 
    runs-on: ubuntu-latest

    steps: 
        - name: checkout repo
          uses: actions/checkout@v4

        - name: use node.js
          uses: actions/setup-node@v4
          with: 
            node-version: '18.x'
          
        - name: Install dependencies
          run: npm install 

        - name: Build application
          run: npm run build

        - name: Run tests
          run: npm test
   
    sca:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm audit
